# Generated by Django 4.2.5 on 2023-09-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.CharField(default="test123", max_length=6),
            preserve_default=False,
        ),
    ]
