# Generated by Django 4.2.5 on 2023-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0003_customuser_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
